/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class graphics_shaders_NativeLib */

#ifndef _Included_graphics_shaders_NativeLib
#define _Included_graphics_shaders_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     graphics_shaders_NativeLib
 * Method:    startGPUTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_graphics_shaders_NativeLib_startGPUTime
  (JNIEnv *, jobject);

/*
 * Class:     graphics_shaders_NativeLib
 * Method:    stopGPUTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_graphics_shaders_NativeLib_stopGPUTime
  (JNIEnv *, jobject);

/*
 * Class:     graphics_shaders_NativeLib
 * Method:    getTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_graphics_shaders_NativeLib_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
