/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opengles_android_NativeLib */

#ifndef _Included_opengles_android_NativeLib
#define _Included_opengles_android_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opengles_android_NativeLib
 * Method:    startGPUTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opengles_android_NativeLib_startGPUTime
  (JNIEnv *, jobject);

/*
 * Class:     opengles_android_NativeLib
 * Method:    stopGPUTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opengles_android_NativeLib_stopGPUTime
  (JNIEnv *, jobject);

/*
 * Class:     opengles_android_NativeLib
 * Method:    getTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_opengles_android_NativeLib_getTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
